# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_page_url', models.CharField(max_length=500)),
                ('job_title', models.CharField(max_length=200)),
                ('path_gcs', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('crawler_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobdetails.CrawlerAgent')),
            ],
        ),
        migrations.AddField(
            model_name='jobdata',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobdetails.JobInfo'),
        ),
    ]
