# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
