# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tld', models.CharField(max_length=300)),
                ('job_url', models.CharField(max_length=500)),
                ('job_html_b64', models.TextField()),
            ],
        ),
    ]
