# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleragent',
            name='job_html_b64',
        ),
        migrations.RemoveField(
            model_name='crawleragent',
            name='job_url',
        ),
        migrations.AddField(
            model_name='crawleragent',
            name='name',
            field=models.CharField(default='sfsf', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawleragent',
            name='tld',
            field=models.CharField(max_length=100),
        ),
    ]
