# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20160610_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.CharField(max_length=500)),
                ('path_gcs', models.CharField(max_length=200)),
                ('crawler_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.CrawlerAgent')),
            ],
        ),
    ]
