# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_jobinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 16, 17, 1, 37, 394008, tzinfo=utc)),
        ),
    ]
