# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20160616_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
