# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20160616_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfo',
            old_name='job_url',
            new_name='job_page_url',
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_parent_url',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_title',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
